custom:
  - "https://www.paypal.com/donate/?business=4XDDD3F38QEGJ&no_recurring=1&item_name=Enjoy+using+the+extension%2C+you+can+skip+and+it+will+unlock+the+app+anyways.+it%27s+just+to+show+your+appreciation.&currency_code=USD"
